name: docker-misc-${CONTAINER_NAME}
services:
  depthcrafter:
    image: ${CONTAINER_NAME}:latest
    container_name: ${CONTAINER_NAME}
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ${HF_HOME}:/root/.cache/huggingface
      - ${TORCH_HOME}:/root/.cache/torch
    ports:
      - ${DEPTHCRAFTER_PORT}:7860
    command: gradio app.py
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
